### ISSUE TITLE
Sharing results

### ISSUE THREAD

**Issue by bitemyapp** [chrisdone/advent-2017-maze-rust-haskell#1]
### My machine

```
$ uname -a
Linux chalcis 4.4.0-98-generic #121-Ubuntu SMP Tue Oct 10 14:24:03 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
![screenshot from 2017-12-14 10-28-45](https://user-images.githubusercontent.com/320177/34002979-af07f34a-e0b9-11e7-9d05-b35778bcbbf6.png)

![screenshot from 2017-12-14 10-28-51](https://user-images.githubusercontent.com/320177/34002983-b3b6ceca-e0b9-11e7-839c-c9d6d941b6aa.png)

Lower single-threaded perf than a 6700K or 7700K but otherwise good parallelism.

### Rust

![screenshot from 2017-12-14 10-28-26](https://user-images.githubusercontent.com/320177/34003004-c21b3ba4-e0b9-11e7-8837-124c51d936a2.png)

### Haskell, native codegen

![screenshot from 2017-12-14 10-29-21](https://user-images.githubusercontent.com/320177/34003023-ccd64fb6-e0b9-11e7-9e17-a89db7b6b0d4.png)

### Haskell, LLVM backend

![screenshot from 2017-12-14 10-32-42](https://user-images.githubusercontent.com/320177/34003156-2d4dc446-e0ba-11e7-8c1d-cf858f383420.png)

![screenshot from 2017-12-14 10-32-54](https://user-images.githubusercontent.com/320177/34003160-2fdf36ea-e0ba-11e7-8e4f-fdd62684195d.png)

Seems broadly similar. Would need to setup a criterion harness to get a good sample.

**Comment by chrisdone** [comment]
Ta! Nothing like the claimed half the time then.

**Comment by bitemyapp** [comment]
@chrisdone didn't really seem like something LLVM would excel at anyway. You'd need long runs of numerical operations on lengthy vectors I think. IO or data structure mungey stuff seemed to work equivalently or better with NCG in my experience. YMMV.

**Comment by DanielJoyce** [comment]
Also since you are running through cargo you're timing the cargo startup and fork time as well

**Comment by DanielJoyce** [comment]
Same with stack. Is there a reason the binaries are not run directly?

**Comment by chrisdone** [comment]
I'm not using `time` to measure anything. The timings are from within the program, look at the source.
