### ISSUE TITLE
Don't compare against a debug release of Rust

### ISSUE THREAD

**Issue by davidarmstronglewis** [chrisdone/advent-2017-maze-rust-haskell#2]
Just to keep comparisons fair, try running the Rust version with `cargo run --release`. The additional release flag will let `cargo` know to remove all the debug symbols from the build and do additional optimizations from the final build.

Please also update the Readme to include this.

**Comment by davidarmstronglewis** [comment]
Seems you've just done this. What response time!

**Comment by chrisdone** [comment]
Cheers! I saw your reddit comment.
